export const USER_FIELDS = [
    { name: "ambiguous_nl2sql_not_possible", pos: 1, placeholder: "Do you agree with the classification of nl2sql not possible?", definition: "Given the NL question, Context, and Schema, it is not possible to generate benchmark SQL due to ambiguity." },
    { name: "missing_nl2sql_not_possible", pos: 2, placeholder: "Do you agree with the classification of nl2sql not possible?", definition: "Given the NL question, Context, and Schema, it is not possible to generate benchmark SQL due to missingness." },
    { name: "inaccurate_nl2sql_not_possible", pos: 3, placeholder: "Do you agree with the classification of nl2sql not possible?", definition: "Given the NL question, Context, and Schema, it is not possible to generate benchmark SQL due to inaccuracy." },

    { name: "ambiguous_question", pos: 4, placeholder: "Do you agree with the classification for question ambiguity?", definition: "A question is ambiguous when its phrasing admits multiple plausible interpretations, each corresponding to a different SQL query structure. Ambiguity in the question category arises independently of the underlying schema: the phrasing itself introduces uncertainty about the user’s intent.\n\nFor instance, consider the question 'Who is the best answerer?'. The notion of 'best answerer' is inherently under-specified and can be interpreted in several ways (e.g., most answers, highest acceptance rate, highest average score, etc.), regardless of the schema. While the schema does not create the ambiguity, its available attributes may constrain or bias which interpretations are more plausible, thereby narrowing the space of valid options." },
    { name: "missing_question", pos: 5, placeholder: "Do you agree with the classification for question missingness?", definition: "Question missingness occurs when the ground truth SQL is related to the question but relies on information that is absent from the provided input. In these cases, the question does not supply sufficient detail for an expert or a model to infer the annotated query, even if the overall intent appears aligned. Missingness errors typically arise from incomplete benchmark construction, e.g., missing contextual descriptions, truncated questions, or implicit assumptions, resulting in SQL queries that cannot be justified from the given input."},
    { name: "inaccurate_question", pos: 6, placeholder: "Do you agree with the classification for question inaccuracy?", definition: "Question inaccuracy occurs when the ground truth SQL is not inferable at all from the question and context because it is logically unrelated or contradicts the stated intent, i.e., the annotation encodes semantics that do not correspond to any reasonable interpretation of the question. These errors often stem from mismatched annotations or systematic quality control failures during benchmark curation. As with missingness, even a domain expert with full schema access could not recover the intended query, but in this case because the annotation itself is incorrect, not because the question lacks necessary detail."},

    { name: "ambiguous_projection_fields", pos: 7, placeholder: "Do you agree with the classification for projection fields ambiguity?", definition: "Projection field ambiguity occurs when multiple projections are consistent with the question intent. For example, given a Users table and the question 'return the users', the output could plausibly include user IDs, user names, or the full set of user attributes. Even the representation of a single conceptual field may be ambiguous: user names might appear as separate first_name and last_name columns or as a concatenated full name. Similarly, date related fields may be formatted using DATEPART, DATENAME, or other equivalent functions. Although these variations differ structurally, they correspond to interpretations that are semantically compatible with the question."},
    { name: "missing_projection_fields", pos: 8, placeholder: "Do you agree with the classification for projection fields missingness?", definition: "Projection field missingness occurs when the question aligns with the general intent of the ground truth SQL but fails to provide the information needed to infer the specific projection fields used in the annotation. Here, the issue is not that the projection is incorrect but that it is missing from the question and context. This includes cases where the ground truth SQL selects attributes not mentioned or implied in the input, omits fields clearly required by the question, or applies formatting or transformations (e.g., concatenation, type casting, date extraction) that cannot be inferred from the provided information. As a result, even a domain expert cannot reconstruct the annotated projection without access to additional, unstated details."},
    { name: "inaccurate_projection_fields", pos: 9, placeholder: "Do you agree with the classification for projection fields inaccuracy?", definition: "Projection field inaccuracy arises when the ground truth SQL does not faithfully answer the question because it selects inappropriate fields or includes output columns that contradict the question’s semantics. Unlike missingness, where the projection is plausible but under-specified, inaccuracy reflects a fundamental mismatch: the labeled ground truth SQL projection does not correspond to any reasonable interpretation of the question."},

    { name: "ambiguous_schema_linking", pos: 10, placeholder:"Do you agree with the classification for schema linking ambiguity?", definition: "Schema linking ambiguity occurs when multiple schema elements plausibly correspond to the concepts expressed in the natural language question. Because many databases contain semantically overlapping attributes (e.g., Score, UpVotes, Reputation), or multiple tables that encode related entities (e.g., Users, Posts, Comments), several different mappings from question phrases to schema components may be equally justified. This ambiguity can yield multiple SQL queries, i.e., differing in join paths, selected attributes, or predicate references, that remain consistent with the question’s phrasing and intent."},
    { name: "missing_schema_linking", pos: 11, placeholder: "Do you agree with the classification for schema linking missingness?", definition: "Schema linking missingness arises when the question or provided context omits essential information needed to determine the correct mapping to schema elements. In such cases, the benchmark's ground truth SQL assumes knowledge that is unavailable to both models and domain experts, such as the meaning of categorical codes, the correspondence between aliases and attributes, or the intended join relationships among tables. Without this missing contextual detail, the correct schema mapping and thereby the correct SQL, is not inferrable."},
    { name: "inaccurate_schema_linking", pos: 12, placeholder: "Do you agree with the classification for schema linking inaccuracy?", definition: "Schema linking inaccuracy occurs when the annotated ground truth SQL links to schema elements that do not align with the question’s semantic intent. This includes selecting attributes from the wrong table, using an inappropriate join path, or referencing columns that do not instantiate the concept described in the question. In these cases, the ground truth SQL is not inferrable and incorrect: no reasonable interpretation of the question supports the schema links encoded in the annotated ground truth query."},

    { name: "ambiguous_predicate_value", pos: 13, placeholder:"Do you agree with the classification for predicate value ambiguity?", definition: "Predicate value ambiguity occurs when multiple value assignments are equally plausible interpretations of the question, typically because the user’s phrasing does not uniquely determine the exact constant or boundary to use. This ambiguity often stems from limited knowledge of how values are represented in the database, such as categorical codes, abbreviations, or integer identifiers whose meanings are not provided in the context. Even seemingly straightforward string filters can introduce ambiguity due to case sensitivity or normalization conventions. For example, when querying for 'locally funded' schools, the corresponding filter could reasonably appear as FundingType = 'locally funded', FundingType = 'Locally funded', or FundingType = 'Locally Funded', depending on database conventions. More abstract predicates, such as 'high value' introduce even greater uncertainty, as multiple thresholds or definitions could satisfy the user’s intent." },
    { name: "missing_predicate_value", pos: 14, placeholder: "Do you agree with the classification for predicate value missingness?", definition: "Predicate value missingness arises when the ground truth SQL is broadly related to the question but introduces filtering predicates whose values are not specified or implied by the question or its accompanying context. In these cases, the annotated query uses constants, numeric thresholds, or identifiers that are neither mentioned nor inferable from the question."},
    { name: "inaccurate_predicate_value", pos: 15, placeholder: "Do you agree with the classification for predicate value inaccuracy?", definition: "Predicate value inaccuracy arises when the ground truth SQL queries encode predicate values that contradict the question’s semantics. This includes cases where the predicate does not reflect the intended filter implied by the question or multiple filters are implied in the question but are not applied in the query."},

    { name: "ambiguous_redundancy", pos: 16, placeholder: "Do you agree with the classification for redundancy ambiguity?", definition: "Redundancy ambiguity arises when the question does not clearly indicate whether duplicates should be removed. Phrases such as 'List user locations' admit multiple interpretations: one might reasonably return all locations associated with users (including duplicates), or only the set of distinct locations. Ambiguity also arises when the question relies on presumed, but unstated, uniqueness properties of schema attributes. For instance, while it may seem natural to assume that identifiers are unique, this assumption does not always hold in real-world databases, and the question may not clarify the intended semantics."},
    { name: "missing_redundancy", pos: 17, placeholder: "Do you agree with the classification for redundancy missingness?", definition: "Redundancy missingness arises when the ground truth SQL is broadly aligned with the question’s intent but relies on uniqueness assumptions that are not stated in the question or context. For instance, an annotation may apply DISTINCT or UNIQUE to an identifier column under the assumption that identifiers are unique, without explicitly providing this constraint as contextual information. In such cases, the benchmark omits critical information needed to justify the redundancy handling encoded in the ground truth query."},
    { name: "inaccurate_redundancy", pos: 18, placeholder: "Do you agree with the classification for redundancy inaccuracy?", definition: "Redundancy inaccuracy occurs when the ground truth SQL fails to implement the uniqueness semantics implied by the question or the context. Examples include omitting DISTINCT when the question requests 'unique locations' or including DISTINCT when the question clearly calls for all occurrences."},

    { name: "ambiguous_null", pos: 19, placeholder: "Do you agree with the classification for null ambiguity?", definition: "Null ambiguity occurs when the question under-specifies how missing data should be interpreted in the corresponding SQL. For instance, the request “posts with no comments” may correspond equally plausibly to filtering with CommentCount = 0, CommentCount IS NULL, or a combination both, depending on the database’s representation of missing comment information. Similar ambiguity arises in aggregates such as COUNT, where it may be unclear whether NULL values should be included, excluded, or treated as defaults."},
    { name: "missing_null", pos: 20, placeholder: "Do you agree with the classification for null missingness?", definition: "Null missingness arises when the ground truth SQL relies on null-handling logic that cannot be inferred from the question or provided context. This includes cases where the annotation applies NULL-specific predicates, default substitutions, or aggregate behaviors without specifying the necessary assumptions about the presence or meaning of missing values. Null missingness also occurs when the question aligns with the general intent of the ground truth query but omits information about columns or representations that are essential for determining how NULL values should be handled. As a result, even a domain expert cannot reconstruct the annotated query from the input alone."},
    { name: "inaccurate_null", pos: 21, placeholder: "Do you agree with the classification for null inaccuracy?", definition: "Null inaccuracy arises when the ground truth SQL mishandles null semantics relative to what the question implies. Examples include using = instead of IS NULL for missing values, applying incorrect default substitutions, or improperly excluding nulls from aggregates when inclusion is semantically required."},

    { name: "ambiguous_comparison_operation", pos: 22, placeholder: "Do you agree with the classification for comparison operation ambiguity?", definition: "Comparison operator ambiguity emerges when the phrasing of the question supports multiple equally plausible operator choices. Quantifiers such as 'around', 'roughly', or 'close to' provide no precise numerical boundary, leaving open whether the intended filter should use equality, inequality with tolerances, or range-based predicates. Textual predicates raise similar issues: depending on conventions or context, matching a name or category may appropriately use = or a substring match such as LIKE '%...%'. The correct interpretation often depends on database-specific value formats or implicit domain knowledge that is not present in the benchmark context."},
    { name: "missing_comparison_operation", pos: 23, placeholder: "Do you agree with the classification for comparison operation missingness?", definition: "Comparison operator missingness arises when the ground truth SQL is broadly related to the question but relies on comparison operators, thresholds, or quantifiers that are not specified or implied by the question or its accompanying context. This includes cases where the annotated query introduces arbitrary numeric bounds, implicit ranges, or comparison logic that cannot be inferred from the natural language input."},
    { name: "inaccurate_comparison_operation", pos: 24, placeholder: "Do you agree with the classification for comparison operation inaccuracy?", definition: "Comparison operator inaccuracy occurs when the ground-truth SQL employs operators that directly contradict the semantics implied by the question. Examples include misinterpreting 'nonnegative score' as score > 0 (incorrectly excluding zero), using strict inequalities where inclusive ones are required, or applying substring matching when the question clearly implies exact matching."},

    { name: "ambiguous_equation", pos: 25, placeholder: "Do you agree with the classification for equation ambiguity?", definition: "Equation ambiguity occurs when the question references a metric or derived quantity that admits multiple valid mathematical formulations. For example, terms such as 'profit margin', 'growth rate', or 'average performance' can be computed in several reasonable ways depending on conventions, normalization choices, or denominators. In such cases, multiple SQL equations are semantically compatible with the question, and additional contextual information, i.e., domain conventions or explicit definitions, is required to narrow the interpretation to the specific formulation used in the annotated ground truth query."},
    { name: "missing_equation", pos: 26, placeholder: "Do you agree with the classification for equation missingness?", definition: "Equation missingness arises when the ground truth SQL is broadly aligned with the question’s intent but employs an equation that is not specified or implied by the natural language input. Here, the query may compute a metric that is not in the question. As a result, the annotated equation cannot be reconstructed from the input alone, even by a domain expert."},
    { name: "inaccurate_equation", pos: 27, placeholder: "Do you agree with the classification for equation inaccuracy?", definition: "Equation inaccuracy occurs when the ground truth SQL uses an equation that does not faithfully reflect the metric requested in the question or the information provided in the context. This includes cases where the annotated query applies a formula that contradicts the intended definition of the metric or fails to include an equation explicitly requested by the question."},

    { name: "ambiguous_sort_order", pos: 28, placeholder: "Do you agree with the classification for sort order ambiguity?", definition: "Sort order ambiguity occurs when the question implies that results should be ordered but does not clearly specify the ordering direction. Phrases such as 'top', 'highest', or 'latest' may indicate a ranking criterion, yet leave open whether the sort should be ascending, descending, or even unspecified, depending on implicit conventions. In such cases, the ordering attribute itself may be inferable from the question, but the absence of an explicit direction allows multiple equally plausible interpretations of the intended SQL."},
    { name: "missing_sort_order", pos: 29, placeholder: "Do you agree with the classification for sort order missingness?", definition: "Sort order missingness arises when the ground truth SQL introduces additional ordering attributes or tie-breaking keys that are not specified or implied by the question or its context. For example, if the question asks for 'all users sorted by highest reputation', but the annotated query orders first by reputation and then by username alphabetically, the secondary sort key is missing from the question. As a result, the full ordering encoded in the ground truth query cannot be reconstructed from the input alone."},
    { name: "inaccurate_sort_order", pos: 30, placeholder: "Do you agree with the classification for sort order inaccuracy?", definition: "Sort order inaccuracy, by contrast, occurs when the ground truth SQL contradicts the sorting semantics implied by the question. This includes mislabeling the sort direction (e.g., interpreting 'latest' using ascending order), omitting an ORDER BY clause when the question explicitly requests ranked results, or applying an ordering that conflicts with the intended ranking criterion. "},

    { name: "ambiguous_group_by", pos: 31, placeholder: "Do you agree with the classification for group by ambiguity?", definition: "Group by ambiguity occurs when the question permits multiple plausible grouping choices without providing sufficient cues to disambiguate among them. For example, a request to group 'by user' may reasonably correspond to grouping by a user identifier, a username, or another user-related attribute, each of which yields different aggregation behavior. Temporal groupings introduce similar ambiguity: when a question asks to group 'by date', the intended granularity may range from year, to year–month, to full calendar date, depending on context. These alternatives are structurally distinct yet semantically compatible with the question’s phrasing."},
    { name: "missing_group_by", pos: 32, placeholder: "Do you agree with the classification for group by missingness?", definition: "Group by missingness arises when the ground truth SQL includes grouping keys that are not specified or implied by the question or its context. This includes cases where the annotation introduces additional grouping dimensions, such as secondary attributes or implicit formatting choices that are not mentioned in the natural language input. As a result, the annotated grouping cannot be fully inferred from the question alone."},
    { name: "inaccurate_group_by", pos: 33, placeholder: "Do you agree with the classification for group by inaccuracy?", definition: "Group by inaccuracy occurs when the ground truth SQL contradicts the grouping semantics implied by the question. Examples include omitting grouping dimensions explicitly mentioned in the question, grouping by an incorrect attribute, or using an incomplete grouping set (e.g., grouping by a single column when a composite grouping is required)."},

    { name: "ambiguous_nesting", pos: 34, placeholder: "Do you agree with the classification for nesting ambiguity?", definition: "Nesting ambiguity occurs when the natural language question permits multiple semantically valid nesting scopes, each leading to different logical outcomes. This typically arises from ambiguity in the scope of quantifiers or temporal constraints (e.g., local versus global interpretation). In such cases, the ground truth SQL may reflect a reasonable interpretation of the question, yet alternative nesting structures, i.e., different placements of subqueries or reordering of dependent clauses, remain equally consistent with the question’s phrasing. For example, a question asking about 'users over time' may admit multiple valid nesting strategies depending on how time is scoped or aggregated across subqueries (e.g., grouping by year within an inner query versus applying temporal filters at the outer level), resulting in different but semantically plausible outputs."},
    { name: "missing_nesting", pos: 35, placeholder: "Do you agree with the classification for nesting missingness?", definition: "Nesting missingness arises when the ground truth SQL relies on nesting decisions that are not specified or implied by the question or its context. In these cases, critical information used within inner queries, such as the application of TOP, LIMIT, or filtering conditions, directly influences the results of the outer query, yet the question provides no cues that such nesting behavior is intended. As a result, the annotated query cannot be reliably reconstructed from the input alone, since omitting or relocating these nested operations would materially change the outcome."},
    { name: "inaccurate_nesting", pos: 36, placeholder: "Do you agree with the classification for nesting inaccuracy?", definition: "Nesting inaccuracy occurs when the nesting structure encoded in the ground truth SQL does not align with the semantics of the question. This includes cases where the annotation applies nesting that contradicts the intended scope of aggregation or filtering, as well as cases where nesting is omitted despite being necessary to correctly capture the question’s intent."},
    
    { name: "ambiguous_join", pos: 37, placeholder: "Do you agree with the classification for join ambiguity?", definition: "Join ambiguity occurs when the natural language question supports multiple plausible relational interpretations, either in terms of join paths or join types. For instance, a request to 'list all users and their posts' may reasonably map to an INNER JOIN (returning only users with posts) or a LEFT JOIN (including users without posts), depending on whether unmatched entities should be retained. Similarly, schemas often admit multiple valid join paths between entities via different intermediate tables or foreign-key relationships, each yielding a semantically plausible query. In such cases, additional contextual cues, such as whether absence should be preserved or filtered, are required to disambiguate the intended join structure but are often missing from benchmark annotations."},
    { name: "missing_join", pos: 38, placeholder: "Do you agree with the classification for join missingness?", definition: "Join missingness arises when the ground truth SQL is broadly aligned with the question’s intent but relies on join decisions that cannot be inferred from the question or its accompanying context. This includes cases where the annotation selects a specific join type (e.g., LEFT JOIN vs. INNER JOIN) or intermediate table without any indication in the question that such semantics are required. As a result, the benchmark presupposes knowledge about tuple inclusion, optional relationships, or schema-specific constraints that are unavailable to both models and human experts."},
    { name: "inaccurate_join", pos: 39, placeholder: "Do you agree with the classification for join inaccuracy?", definition: "Join inaccuracy occurs when the ground truth SQL encodes join semantics that contradict the intent of the question. Examples include using an INNER JOIN where the question clearly implies inclusion of entities with no matching records, selecting a LEFT or RIGHT JOIN when only matched entities are requested, joining on incorrect keys or tables altogether, or applies join logic that contradicts the intended semantics of the question. "},
    
    { name: "ambiguous_aggregation", pos: 40, placeholder: "Do you agree with the classification for aggregation ambiguity?", definition: "Aggregation ambiguity occurs when the phrasing of the question supports multiple plausible aggregation choices. Terms such as 'statistics', 'distribution', or 'summary' do not uniquely identify which aggregates should be computed, leaving open whether the intended output should include counts, averages, extrema, or a combination thereof. In such cases, several aggregation operators (or sets of operators) are equally consistent with the question, and additional contextual cues are required to disambiguate the intended computation."},
    { name: "missing_aggregation", pos: 41, placeholder: "Do you agree with the classification for aggregation missingness?", definition: "Aggregation missingness arises when the ground truth SQL is broadly aligned with the question’s semantics but includes aggregation operations that are not specified or implied by the question or its context. For example, if a question asks only for an average but the annotated query additionally returns the minimum and maximum values, then the latter aggregates are missing from the natural language input. As a result, the full set of aggregations encoded in the ground truth query cannot be inferred from the input alone."},
    { name: "inaccurate_aggregation", pos: 42, placeholder: "Do you agree with the classification for aggregation inaccuracy?", definition: "Aggregation inaccuracy occurs when the ground truth SQL fails to represent the aggregation semantics implied by the question. This includes cases where the annotation applies an incorrect aggregate (e.g., using SUM instead of AVG), omits an aggregate explicitly requested by the question, or applies aggregation at an incorrect granularity due to improper grouping logic. "},

    { name: "ambiguous_temporal_predicate", pos: 43, placeholder: "Do you agree with the classification for temporal predicate ambiguity?", definition: "Temporal ambiguity occurs when the question uses imprecise or relative time expressions that admit multiple plausible interpretations. Phrases such as 'recent', 'last quarter', 'older', or 'newer' do not define explicit reference windows, leaving open how the temporal boundaries should be computed. For example, 'recent' may refer to the past week, month, or year depending on context, while 'last quarter' depends on the assumed calendar and reference date. Resolving such ambiguity typically requires additional contextual information (e.g., a reference timestamp, business calendar, or domain-specific convention) that is not provided in the benchmark."},
    { name: "missing_temporal_predicate", pos: 44, placeholder: "Do you agree with the classification for temporal predicate missingness?", definition: "Temporal missingness arises when the ground truth SQL is broadly aligned with the question’s intent but relies on temporal details that are not specified or inferable from the question or its accompanying context. This includes cases where the ground truth query includes specific date ranges, comparison thresholds, or formatting assumptions (e.g., dates encoded as YYYYMM integers) that are not mentioned in the natural language input. In such cases, the annotated temporal logic cannot be reconstructed from the question alone, even by a domain expert."},
    { name: "inaccurate_temporal_predicate", pos: 45, placeholder: "Do you agree with the classification for temporal predicate inaccuracy?", definition: "Temporal inaccuracy  occurs when the ground truth SQL applies temporal predicates that contradict the semantics implied by the question. Examples include filtering on an incorrect year, using outdated reference periods, or misinterpreting relative expressions (e.g., applying 'this year' to 2023 when the dataset context clearly indicates 2026). Such inaccuracies misrepresent the intended temporal scope and undermine evaluation by penalizing models that correctly interpret the question’s temporal semantics while deviating from flawed benchmark annotations."},

    { name: "ambiguous_db_number", pos: 46, placeholder: "Do you agree with the classification for database number ambiguity?", definition: "DB number ambiguity occurs when the question uses qualitative or vague quantifiers without specifying an explicit numeric value. For example, phrases such as 'top users', 'most popular posts', or 'best comments' indicate a ranking but do not define how many results should be returned. In these cases, multiple numeric cutoffs are equally plausible, and additional contextual cues are required to determine the intended limit."},
    { name: "missing_db_number", pos: 47, placeholder: "Do you agree with the classification for database number missingness?", definition: "DB number missingness arises when the ground truth SQL introduces a numeric result limit that cannot be inferred from the question or its accompanying context. This includes cases where the annotated query applies TOP, LIMIT, or similar constructs despite the absence of any corresponding cue in the natural language input."},
    { name: "inaccurate_db_number", pos: 48, placeholder: "Do you agree with the classification for database number inaccuracy?", definition: "DB number inaccuracy, by contrast, occurs when the ground truth SQL misrepresents the numeric constraints implied by the question. Examples include using an incorrect cutoff value (e.g., returning the top 2000 results instead of the top 200), omitting a result limit when the question explicitly specifies one, or applying a limit that contradicts the stated intent."},
];